# Generated by Django 4.2.2 on 2024-11-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('contact_person', models.CharField(max_length=120)),
                ('package', models.CharField(max_length=120)),
                ('adult', models.PositiveIntegerField()),
                ('child', models.PositiveIntegerField()),
                ('infant', models.PositiveIntegerField()),
                ('foc', models.PositiveIntegerField()),
                ('tour_date', models.DateField()),
                ('tour_time', models.TimeField()),
                ('pickup_location', models.CharField(max_length=200)),
                ('guest_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('payment_ref_no', models.CharField(max_length=50)),
                ('room_no', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('special_requirements', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('package_code', models.CharField(max_length=20)),
                ('package_title', models.CharField(max_length=30)),
                ('package_city', models.CharField(max_length=30)),
                ('web_id', models.CharField(max_length=200)),
                ('web_sku', models.CharField(max_length=200)),
                ('website_link', models.CharField(max_length=300)),
                ('short_description', models.TextField(max_length=300)),
                ('highlights', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('inclusions', models.CharField(max_length=500)),
                ('exclusions', models.CharField(max_length=500)),
                ('transportation', models.CharField(choices=[('Sharing', 'Sharing'), ('Private', 'Private'), ('Without Transfer', 'Without Transfer'), ('Tickets Only', 'Tickets Only')], max_length=30)),
                ('open_hours', models.CharField(max_length=30)),
                ('sunday', models.BooleanField(blank=True, default=True, null=True)),
                ('monday', models.BooleanField(blank=True, default=True, null=True)),
                ('tuesday', models.BooleanField(blank=True, default=True, null=True)),
                ('wednesday', models.BooleanField(blank=True, default=True, null=True)),
                ('thursday', models.BooleanField(blank=True, default=True, null=True)),
                ('friday', models.BooleanField(blank=True, default=True, null=True)),
                ('saturday', models.BooleanField(blank=True, default=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('adult_rate', models.CharField(max_length=20)),
                ('child_rate', models.CharField(max_length=20)),
                ('infant_rate', models.CharField(max_length=20)),
                ('adult_age', models.CharField(max_length=10)),
                ('child_age', models.CharField(max_length=10)),
                ('infant_age', models.CharField(max_length=10)),
                ('image_link', models.CharField(max_length=600)),
                ('video_link', models.CharField(max_length=600)),
                ('language', models.ManyToManyField(to='admin_dashboard.language')),
                ('package_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.category')),
            ],
        ),
        migrations.CreateModel(
            name='Status_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.package')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tl_number', models.PositiveBigIntegerField()),
                ('vat_number', models.PositiveBigIntegerField()),
                ('address1', models.CharField(max_length=100)),
                ('city1', models.CharField(max_length=100)),
                ('state1', models.CharField(max_length=100)),
                ('country1', models.CharField(max_length=100)),
                ('pincode1', models.PositiveIntegerField()),
                ('phone1', models.PositiveIntegerField()),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city2', models.CharField(blank=True, max_length=100, null=True)),
                ('state2', models.CharField(blank=True, max_length=100, null=True)),
                ('country2', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode2', models.PositiveIntegerField(blank=True, null=True)),
                ('phone2', models.PositiveIntegerField(blank=True, null=True)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_designation', models.CharField(max_length=100)),
                ('contact_mobile', models.PositiveIntegerField()),
                ('contact_whatsapp', models.PositiveIntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('trade_license', models.CharField(max_length=200)),
                ('vat_certificate', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.PositiveBigIntegerField()),
                ('iban', models.CharField(max_length=200)),
                ('swift', models.CharField(max_length=200)),
                ('routing_number', models.PositiveBigIntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.status_type')),
                ('supplier_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.supplier_type')),
            ],
        ),
        migrations.CreateModel(
            name='Package_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.status_type'),
        ),
        migrations.CreateModel(
            name='Hero_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Hero_images/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.package')),
            ],
        ),
    ]
