# Generated by Django 4.2.2 on 2025-01-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_allocation',
            name='adultprice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier_allocation',
            name='childprice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier_allocation',
            name='infantprice',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
