# Generated by Django 4.2.2 on 2024-11-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='account_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='routing_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tl_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.PositiveIntegerField(),
        ),
    ]
