# Generated by Django 4.2.2 on 2024-12-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_trip_details',
            name='remark',
            field=models.CharField(max_length=500),
        ),
    ]
