# Generated by Django 4.2.2 on 2025-01-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_trip_details',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
