# Generated by Django 4.2.2 on 2024-12-27 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_booking_trip_details_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.payment_mode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.status_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='whatsapp_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
