# Generated by Django 4.2.2 on 2024-11-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_supplier_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='supplier',
            field=models.ManyToManyField(blank=True, null=True, to='admin_dashboard.supplier'),
        ),
    ]
