# Generated by Django 4.2.2 on 2024-12-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.CharField(default='mujeeb', max_length=100),
        ),
    ]
