# Generated by Django 4.2.2 on 2024-12-27 09:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_booking_payment_mode_booking_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.status_type'),
            preserve_default=False,
        ),
    ]
