# Generated by Django 4.2.2 on 2024-11-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_package_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='supplier',
        ),
        migrations.CreateModel(
            name='Supplier_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.package')),
                ('supplier', models.ManyToManyField(to='admin_dashboard.supplier')),
            ],
        ),
    ]
