# Generated by Django 4.2.2 on 2025-01-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_booking_trip_details_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_trip_details',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking_trip_details',
            name='include',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking_trip_details',
            name='vat',
            field=models.FloatField(default=5),
        ),
    ]
