# Generated by Django 4.2.2 on 2024-12-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_alter_booking_booked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact_person',
        ),
    ]
