# Generated by Django 4.2.2 on 2024-11-19 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_remove_package_supplier_supplier_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_designation',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_mobile',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_whatsapp',
        ),
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('whatsapp', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.supplier')),
            ],
        ),
    ]
