# Generated by Django 4.2.2 on 2024-11-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_remove_supplier_contact_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
