# Generated by Django 4.2.2 on 2024-12-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_company_contact_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_mode',
            fields=[
                ('payment_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
