# Generated by Django 4.2.2 on 2024-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0011_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_mode',
            name='payment_mode',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
