# Generated by Django 4.2.2 on 2024-12-14 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_alter_payment_mode_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('driver_type', models.CharField(choices=[('Limousine', 'Limousine'), ('Transportation', 'Transportation'), ('Tourism', 'Tourism'), ('Stretch limo', 'Stretch limo')], max_length=100)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_brand', models.CharField(max_length=100)),
                ('vehicle_year', models.CharField(max_length=10)),
                ('mobile1', models.PositiveIntegerField()),
                ('mobile2', models.PositiveIntegerField()),
                ('whatsapp1', models.PositiveIntegerField()),
                ('whatsapp2', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_registration', models.CharField(max_length=100)),
                ('rc_expiry', models.DateField()),
                ('dl_number', models.CharField(max_length=100)),
                ('dl_expiry', models.DateField()),
                ('passport_number', models.CharField(max_length=100)),
                ('passport_expiry', models.DateField()),
                ('emirates_id_number', models.CharField(max_length=100)),
                ('emirates_id_expiry', models.DateField()),
                ('visa_number', models.CharField(max_length=100)),
                ('visa_expiry', models.DateField()),
                ('vehicle_rc', models.FileField(upload_to='driver_vehicle_rc/')),
                ('insurance', models.FileField(upload_to='driver_vehicle_insurance/')),
                ('driving_license', models.FileField(upload_to='driving_license/')),
                ('passport', models.FileField(upload_to='driver_passport/')),
                ('emirates_id', models.FileField(upload_to='driver_emirates_id/')),
                ('visa', models.FileField(upload_to='driver_visa/')),
                ('photos', models.FileField(upload_to='driver_photos/')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.status_type')),
            ],
        ),
    ]
