# Generated by Django 4.2.2 on 2024-12-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0015_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pincode1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pincode2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='routing_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tl_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='trade_license',
            field=models.FileField(upload_to='trade_license/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_certificate',
            field=models.FileField(upload_to='vat_certificate/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(max_length=100),
        ),
    ]
