# Generated by Django 4.2.2 on 2024-12-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0016_alter_supplier_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='pincode2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
