# Generated by Django 4.2.2 on 2024-12-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0017_alter_supplier_pincode2'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
