# Generated by Django 4.2.2 on 2024-12-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0018_package_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booked_date', models.DateField(auto_now_add=True)),
                ('booked_by', models.CharField(default='test by mujeeb', max_length=100)),
                ('booking_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('payment_ref_no', models.CharField(max_length=50)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.company')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.company_contact_details')),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
