# Generated by Django 4.2.2 on 2024-12-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0019_booking_delete_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='adult',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='child',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='drop_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='foc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='infant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='pickup_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='pickup_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='remark',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='room_no',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='time',
            field=models.BooleanField(default=True),
        ),
    ]
