# Generated by Django 4.2.2 on 2024-12-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0020_category_adult_category_child_category_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Trip_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('trip_time', models.TimeField()),
                ('no_of_adult', models.PositiveIntegerField()),
                ('no_of_child', models.PositiveIntegerField()),
                ('no_of_infant', models.PositiveIntegerField()),
                ('no_of_foc', models.PositiveIntegerField()),
                ('room_no', models.CharField(max_length=10)),
                ('pickup_location', models.CharField(max_length=100)),
                ('drop_location', models.CharField(max_length=100)),
                ('pickup_time', models.TimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.booking')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.category')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.package')),
            ],
        ),
    ]
